### ISSUE TITLE
Better integrated logging in cache

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cacheddownloader#11]
In the REP we would like to see debug/info/error information in the logs coming from the cached downloader.

There is no messages to indicate problems with the cacheddownloader in the rep to debug cache issues.

Can we have the standard logger used in the cache

**Comment by ematpl** [comment]
Thanks, @andrew-edgar, could you elaborate on precisely what diagnostic information you'd like to see from those logs?

Best,
Eric

**Comment by andrew-edgar** [comment]
We would like to see size of the cache.  when we fail to save to the cache or when downloads fail.  what file is failing.  right now nothing from the cachedownloader goes to the logs on the cell to be able to see any failure case.  We also do checksums in here and we would like to see any checksum issues in there as well.

**Comment by ematpl** [comment]
Hey, @andrew-edgar,

We recently added a logger argument to the cacheddownloader public methods to do some amount of logging inside the file cache. I'll close this out, but if there is additional specific logging you'd like to see please feel free to submit a PR.

Best,
Eric
