### ISSUE TITLE
Symlinks not Correctly Extracted

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cacheddownloader#12]
One of our buildpacks has symbolic links in the tar archive.  When extracting this for a directory bind mount it is not correctly extracted.

If we look at this https://github.com/cloudfoundry/cacheddownloader/blob/05e99061a866574a7d35036b1b9774c042da0732/file_cache.go#L421

The code only manages regular files as well as directories.  We need to add support for symbolic links.  

We will get started on a PR for this shortly.  Has this been seen in any other environments?

**Comment by ematpl** [comment]
Fixed in [Diego v1.6.1](https://github.com/cloudfoundry/diego-release/releases/tag/v1.6.1).
