### ISSUE TITLE
replace_windows is now obsolete in go 1.5

### ISSUE THREAD

**Issue by mavenraven** [cloudfoundry/cacheddownloader#8]
https://github.com/cloudfoundry-incubator/cacheddownloader/blob/master/replace_windows.go

https://github.com/golang/go/commit/92c57363e0b4d193c4324e2af6902fe56b7524a0

**Comment by ematpl** [comment]
Thanks, @mavenraven! Are you building the cell components against Go 1.5 on Windows now?

**Comment by ematpl** [comment]
Forgot to close this issue after the corresponding story was accepted.
